/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.addController;
import javax.swing.JOptionPane;
import controller.deleteControl;
import controller.updateController;

/**
 *
 * @author hp
 */
public class student extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        age = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        conno = new javax.swing.JLabel();
        Address = new javax.swing.JTextField();
        ConNo = new javax.swing.JTextField();
        grade = new javax.swing.JLabel();
        Grade = new javax.swing.JComboBox<>();
        Age = new javax.swing.JTextField();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        Gender = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        back = new javax.swing.JButton();
        update = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        Birthday = new javax.swing.JTextField();
        birthday = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        name = new javax.swing.JLabel();

        jTextField6.setText("jTextField6");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        jButton4.setText("jButton4");

        jButton5.setText("jButton5");
        jButton5.setAutoscrolls(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 50)); // NOI18N
        jLabel1.setText("Student");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 240, 60));

        id.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        id.setText("Id :");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 150, 30));

        address.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        address.setText("Addres :");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 90, 30));

        age.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        age.setText("Age :");
        jPanel1.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 70, 30));

        gender.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gender.setText("Gender :");
        jPanel1.add(gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, -1, -1));

        conno.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        conno.setText("Contact No :");
        jPanel1.add(conno, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 130, 30));

        Address.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 170, 30));

        ConNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        ConNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConNoActionPerformed(evt);
            }
        });
        jPanel1.add(ConNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 550, 180, 30));

        grade.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        grade.setText("Grade :");
        jPanel1.add(grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 630, 110, 30));

        Grade.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1A", "1B", "1C" }));
        Grade.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        Grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeActionPerformed(evt);
            }
        });
        jPanel1.add(Grade, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 120, 30));

        Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 170, 30));

        kGradientPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        kGradientPanel1.setkEndColor(new java.awt.Color(153, 153, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 102));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Gender.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Male", "Female" }));
        Gender.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel1.add(Gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 120, 30));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton6.setText("Add");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 100, 30));

        Delete.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Delete.setText("Delete");
        Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 100, 30));

        back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        back.setText("Back");
        back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        kGradientPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 100, 30));

        update.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        update.setText("Update");
        update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        kGradientPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 500, 100, 30));

        submit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        kGradientPanel1.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 100, -1));

        Birthday.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        kGradientPanel1.add(Birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 170, 30));

        birthday.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        birthday.setText("Birthday :");
        kGradientPanel1.add(birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 120, 30));

        Id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Id, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 170, 30));

        Name.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 170, 30));

        name.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        name.setText("Name :");
        kGradientPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, -1));

        jPanel1.add(kGradientPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GradeActionPerformed

    private void ConNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConNoActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    
    public class Student extends javax.swing.JFrame {

    public Student() {
        initComponents();
    }

    private void initComponents() {
        // Your initComponents code here
    }

   

    // Other methods and variables remain unchanged
}
    
    
    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        
        String idno = Id.getText();
        String name = Name.getText();
        String address = Address.getText();
        String age = Age.getText();
        String birthday = Birthday.getText();
        String gender = (String)Gender.getSelectedItem();
        String contactNo = ConNo.getText();
        String grade = (String)Grade.getSelectedItem();
        
        try {
            int id = Integer.parseInt(idno);
            int aag = Integer.parseInt(age);
            int conNo = Integer.parseInt(contactNo);
            addController obj = new addController();
            obj.studentdetails(id, name, address, aag, birthday, gender, conNo, grade);
        } catch (NumberFormatException e) {
            e.printStackTrace();
        }
    }
        
       /*
        String idno = Id.getText();
        String name = Name.getText();
        String address = Address.getText();
        String age = Age.getText();
        String birthday = Birthday.getText();
        String gender = (String)Gender.getSelectedItem();
        String contactNo = ConNo.getText();
        String grade = (String)Grade.getSelectedItem();
        try{
            int id = Integer.parseInt(idno );
            int aag = Integer.parseInt(age);
            int conNo = Integer.parseInt(contactNo);
            addController obj = new addController();
            obj.studentdetails(id,name,address,aag,birthday,gender,conNo,grade);
            
            
        }catch(NumberFormatException e) {
            
        }
        
       
    }//GEN-LAST:event_submitActionPerformed
 
    */
    
    
    
    
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        String idText = Id.getText(); 
        String priceText = Name.getText();  
        String quantityText = Address.getText();
        String description = ConNo.getText();
        
    
    try {
            int id = Integer.parseInt(idText);
            int quantity = Integer.parseInt(description);

            updateController controller = new updateController();
            controller.update(id,priceText,quantityText,quantity);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         studenttable obj = new studenttable();
         obj.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String idText = Id.getText();
      
       try {
            int id = Integer.parseInt(idText);

            deleteControl controller = new deleteControl();
            controller.delete(id);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid numerical values.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Home obj = new Home ();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Birthday;
    private javax.swing.JTextField ConNo;
    private javax.swing.JButton Delete;
    private javax.swing.JComboBox<String> Gender;
    private javax.swing.JComboBox<String> Grade;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel address;
    private javax.swing.JLabel age;
    private javax.swing.JButton back;
    private javax.swing.JLabel birthday;
    private javax.swing.JLabel conno;
    private javax.swing.JLabel gender;
    private javax.swing.JLabel grade;
    private javax.swing.JLabel id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JButton submit;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
